const dxData = [
    {
        shortname: 'AAA3',
        name: 'Utopias: Navigating Without Coordinates',
        description: 'Is a collective utopia possible?',
        year: '2020',
        url: "https://utopias.aaasoftwa.re/",
        geo: '../res/utopias.glb',
        background: "",
    },
    {
        shortname: 'AAA2',
        name: 'Data Mutations',
        description: 'We mutate each other',
        year: '2017',
        url: "https://data-mutations.aaasoftwa.re/",
        geo: '../res/datamutations.glb',
        background: "",
    },
    {
        shortname: 'HZ',
        name: 'Homezome',
        description: 'Build crap',
        year: '2016',
        url: "www.google.com",
        geo: '../res/homezome.glb',
        background: "",
    },
    {
        shortname: 'AAA1',
        name: 'Dystropicana',
        description: 'Multimedia archipelago',
        year: '2016',
        url: "https://aaasoftwa.re/dystropicana/",
        geo: '../res/dystropicana.glb',
        background: "",
    },
];