const dxData = [
    {
        shortname: 'UTO',
        name: 'Utopias: Navigating Without Coordinates',
        description: 'Is a collective utopia possible?',
        year: '2020',
        url: "https://utopias.aaasoftwa.re/",
        geo: '../res/utopias.glb',
        background: '../imgs/utopias.png',
    },
    {
        shortname: 'DMU',
        name: 'Data Mutations',
        description: 'We mutate each other',
        year: '2017',
        url: "https://data-mutations.aaasoftwa.re/",
        geo: '../res/datamutations.glb',
        background: '../imgs/datamutations.png',
    },
    {
        shortname: 'HZM',
        name: 'Homezome',
        description: 'Build crap',
        year: '2016',
        url: "www.google.com",
        geo: '../res/homezome.glb',
        background: '../imgs/homezome.png',
    },
    {
        shortname: 'DYS',
        name: 'Dystropicana',
        description: 'Multimedia archipelago',
        year: '2016',
        url: "https://aaasoftwa.re/dystropicana/",
        geo: '../res/dystropicana.glb',
        background: '../imgs/dystropicana.png',
    },
];